spring:
  datasource:
    url: jdbc:postgresql://arloid.c8mjmsowzws0.us-west-2.rds.amazonaws.com:5432/alarm_call
    username: arloid
    password: arloidpass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.change-set/liquibase.xml
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibername:
        temp:
          use_jdbc_metadata_defaults: false

twilio:
  sid: ACfb28f9c33fc8c2d2379ec331ad282998
  token: 151f008b881a76f59c761adde15e95fe
  number: 2513334379
  alarm-endpoint: http://ec2-54-244-191-28.us-west-2.compute.amazonaws.com:8080/alarms/
  tracker-endpoint: http://ec2-54-244-191-28.us-west-2.compute.amazonaws.com:8080/calls/closes/

amazon:
  s3:
    access_key: AKIAITCZH4U66KT7VPTQ
    secret_key: YCxPORIhVCpXojjoMeFJoMYgaTlZj9TwtOleYx
    bucket: alarm-twiml
alarm:
  internal:
    track-file: mp3/track.mp3
    max-call-attempts: 4
logging:
  file: alarm-call.log