#server:
#  servlet:
#    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alarm_call
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 21
      minimum-idle: 11
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
alarm:
  internal:
    max-call-attempts: 2